name: my_game
description: "A simple game using Flutter"
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flame: ^1.15.0
  flame_splash_screen: ^0.2.0
  matcher: ^0.12.16
  material_color_utilities: 0.5.0
  meta: 1.10.0
  path: 1.8.3
  test_api: 0.6.1
  web: 0.3.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

assets:
  assets/:
  - turtle1.png
  - turtle2.png
  - trash.png
  - background.png
  - arrow.png
  - background25.png
